# Generated by Django 4.2.6 on 2023-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=70)),
                ('marks', models.CharField(max_length=70)),
                ('pass_date', models.DateField()),
            ],
        ),
    ]
