# Generated by Django 4.2.6 on 2023-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0004_student_admdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(),
        ),
    ]
