# Generated by Django 4.2.6 on 2023-10-09 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0005_alter_student_admdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
