# Generated by Django 4.2.6 on 2023-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0006_alter_student_admdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admdatetime',
        ),
        migrations.AddField(
            model_name='student',
            name='admindatetime',
            field=models.DateTimeField(default=True),
        ),
    ]
