# Generated by Django 4.2.6 on 2023-10-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0008_alter_student_admindatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admindatetime',
            field=models.DateTimeField(default=True),
        ),
    ]
