# Generated by Django 4.2.6 on 2023-10-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0009_alter_student_admindatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admindatetime',
        ),
    ]
