# Generated by Django 4.2.6 on 2023-10-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0010_remove_student_admindatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pass_date',
        ),
    ]
