# Generated by Django 4.2.6 on 2023-10-09 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0011_remove_student_pass_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(default='default value', verbose_name=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='pass_date',
            field=models.DateField(default='default value'),
        ),
    ]
