# Generated by Django 4.2.6 on 2023-10-09 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0012_student_admdatetime_student_pass_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(default='default value', verbose_name=datetime.datetime(2023, 10, 9, 17, 5, 25, 612496)),
        ),
    ]
