# Generated by Django 4.2.6 on 2023-10-09 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0013_alter_student_admdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(default='default value', verbose_name=datetime.datetime(2023, 10, 9, 17, 6, 56, 664537)),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass_date',
            field=models.DateField(default='2023-10-09'),
        ),
    ]
