# Generated by Django 4.2.6 on 2023-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('roll', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=70)),
                ('marks', models.CharField(max_length=70)),
                ('pass_date', models.DateField()),
                ('admdatetime', models.DateTimeField()),
            ],
        ),
    ]
